# Generated by Django 3.0.6 on 2020-05-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200510_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='£20.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Shoe', 'Shoe')], default='Top', max_length=128),
        ),
    ]
